import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'appsProject.dashboard',
        path: `${APP_PREFIX_PATH}/project/dashboard`,
        title: 'Dashboard',
        translateKey: 'nav.appsProject.dashboard',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsCrm.workers',
        path: `${APP_PREFIX_PATH}/crm/workers`,
        title: 'Workers',
        translateKey: 'nav.appsCrm.workers',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.clients',
        path: `${APP_PREFIX_PATH}/crm/clients`,
        title: 'Clients',
        translateKey: 'nav.appsAccount.clients',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.contracts',
        path: `${APP_PREFIX_PATH}/crm/contracts`,
        title: 'Contracts',
        translateKey: 'nav.appsAccount.contracts',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.agencies',
        path: `${APP_PREFIX_PATH}/crm/agencies`,
        title: 'Agencies',
        translateKey: 'nav.appsAccount.agencies',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.camps',
        path: `${APP_PREFIX_PATH}/crm/camps`,
        title: 'Camps',
        translateKey: 'nav.appsAccount.camps',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsCrm.religions',
        path: `${APP_PREFIX_PATH}/crm/religions`,
        title: 'Religions',
        translateKey: 'nav.appsCrm.religions',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.countries',
        path: `${APP_PREFIX_PATH}/crm/countries`,
        title: 'Countries',
        translateKey: 'nav.appsAccount.countries',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.steps',
        path: `${APP_PREFIX_PATH}/crm/steps`,
        title: 'Steps',
        translateKey: 'nav.appsAccount.steps',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
    {
        key: 'appsAccount.attachments',
        path: `${APP_PREFIX_PATH}/crm/attachments`,
        title: 'Attachments',
        translateKey: 'nav.appsAccount.attachments',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
    },
]

export default appsNavigationConfig
